### ISSUE TITLE
Dynamically load $rootScope.baseUrl from a Platform.sh environment variables

### ISSUE THREAD

**Issue by GuGuss** [GuGuss/headless-drupal8-angular-platformsh#1]
The `$rootScope.baseUrl` is currently hardcoded [here](https://github.com/GuGuss/headless-drupal8-angular-platformsh/blob/master/angular/app/scripts/app.js#L22).

It needs to be loaded from the `PLATFORM_ROUTES` environment variable provided by Platform.sh.

In PHP, that would be:

```
$routes = json_decode(base64_decode($_ENV['PLATFORM_ROUTES']), TRUE);
$rootScope.baseUrl = key($routes);
```

**Comment by ralt** [comment]
Since the only dynamic part is during `grunt`'s build, it's the only part where you can get the non-hardcoded url. You could create a small grunt task that creates a file and include this file in your app.

**Comment by GuGuss** [comment]
The problem is that `PLATFORM_ROUTES` is a runtime variable, which is not available during the build process.

So this custom Grunt task would return `undefined` because this `process.env.PLATFORM_ROUTES` is not available yet:

```
// Get PLATFORM_ROUTES to populate the Angular $rootScope.baseUrl.
  grunt.registerTask('platform_routes', 'Get PLATFORM_ROUTES', function() {
    var base64 = require('base-64');
    grunt.log.writeln( base64.decode(process.env.PLATFORM_ROUTES) );
  });
```

**Comment by ralt** [comment]
The best way is probably to write a file in a shared folder at deploy time, that just defines the constant. This way, your current code can just load this module and use its value.

**Comment by GuGuss** [comment]
Fixed here: https://github.com/GuGuss/headless-drupal8-angular-platformsh/commit/3de65a49d628623dd1cd382cb7ed548308c94866
